# Generated by Django 5.1 on 2024-09-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('idmaster', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='AGENTE-IRKO', max_length=50)),
                ('descritivo', models.CharField(default='O que farei?', max_length=100)),
                ('max_token', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrucao', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrucoes', to='agente.agente')),
            ],
        ),
        migrations.CreateModel(
            name='PermissaoAgenteEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agente.agente')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresas')),
            ],
        ),
    ]
