# Generated by Django 5.1 on 2024-09-16 21:23

import agente.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoInstrucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=agente.models.agente_base_conhecimento_path)),
                ('id_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='agente.agente')),
            ],
        ),
    ]
