# Generated by Django 5.1 on 2024-09-16 21:44

import agente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0002_arquivoinstrucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='logo_agente',
            field=models.ImageField(blank=True, null=True, upload_to=agente.models.agente_logo_path),
        ),
    ]
