# Generated by Django 5.1 on 2024-09-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0003_agente_logo_agente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArquivoInstrucao',
            new_name='baseConhecimento',
        ),
    ]
