# Generated by Django 5.1 on 2024-09-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0004_rename_arquivoinstrucao_baseconhecimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseconhecimento',
            name='id_agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_conhecimento', to='agente.agente'),
        ),
    ]
