# Generated by Django 5.1 on 2024-09-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmaster', models.CharField(max_length=30)),
                ('id_usuario', models.CharField(max_length=30)),
                ('autor', models.CharField(choices=[('2', 'user'), ('1', 'system')], max_length=1)),
                ('mensagem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agente.agente')),
            ],
        ),
    ]
