# Generated by Django 5.1 on 2024-09-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='autor',
            field=models.CharField(choices=[('1', 'system'), ('2', 'user')], max_length=1),
        ),
    ]
