# Generated by Django 5.1 on 2024-09-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='autor',
            field=models.CharField(choices=[('2', 'user'), ('1', 'system')], max_length=1),
        ),
    ]
